const { default: mongoose } = require("mongoose")
const mangoose=require("mongoose")
require("../model/config")
const productCollection=mangoose.Schema({
    productName:{
        type:String,
        required:true
    },
    productCategory:{
        type:String,
        required:true
    },
    productDescription:{
        type:String,
        required:true
    },
    variant:[{
        productsize:{
            type:String,
            // required:true
        },
        productcolour:{
            type:String,
            // required:true
        }
    }],
    quantity:{
        type:Number,
        // required:true
    },
    productImage:[{
        image1:{
            type:String
        },
        image2:{
            type:String
        },
        image3:{
            type:String
        },
        image4:{
            type:String
        },
        image5:{
            type:String
        },
        image0:{
            type:String
        },
    }],
    image360degree:[{
        image3601:{
            type:String
        },
        image3602:{
            type:String
        },
        image3603:{
            type:String
        },
        image3604:{
            type:String
        },
        image3605:{
            type:String
        },
        image3600:{
            type:String
        },
    }],

    status:{
        type:String,
        enum:["draft","published","outOfStock","lowStock"]
    },
    stockCount:{
        type:Number
    },
    specification:[{
      
        brand:{
            type:String
        },
        MadeIn:{
            type:String
        },
        StrapMaterial:{
            type:String
        },
        waterResistant:{
            type:Boolean
        },
        display:{
            type:String
        },
        screenSize:{
            type:String
        },
        fastCharge:{
            type:Boolean
        },
        battery:{
            type:String
        },
        weight:{
            type:String
        },
        sleepTracker:{
            type:Boolean
        },
        warranty:{
            type:String
        },

    }]
    ,
    productPrice:{
        type:Number,
        required:true
    },
    rating:{
        type:Number
    },
    addedDate:{
        type:Date
    }

})
const productData=mongoose.model("products",productCollection);
module.exports=productData;